In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
import scipy as sp
import scipy.sparse
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
from generate_matrices import band_mx

In [5]:
band_mx(5, 3, half_band_size=3)

[-24.98373105 -25.75552193 -22.96455279 -26.38817053 -24.62220085
 -26.37779635 -24.94882001]
[[-24.98373105 -24.98373105 -24.98373105]
 [-25.75552193 -25.75552193 -25.75552193]
 [-22.96455279 -22.96455279 -22.96455279]
 [-26.38817053 -26.38817053 -26.38817053]
 [-24.62220085 -24.62220085 -24.62220085]
 [-26.37779635 -26.37779635 -26.37779635]
 [-24.94882001 -24.94882001 -24.94882001]]
[-3 -2 -1  0  1  2  3]


<5x3 sparse matrix of type '<class 'numpy.float64'>'
	with 14 stored elements (7 diagonals) in DIAgonal format>

In [6]:
band_mx(5, 3, half_band_size=3, return_sparse=False)

[-25.07107905 -26.09829239 -24.71923002 -25.01614101 -24.92119495
 -24.46415925 -24.18835058]
[[-25.07107905 -25.07107905 -25.07107905]
 [-26.09829239 -26.09829239 -26.09829239]
 [-24.71923002 -24.71923002 -24.71923002]
 [-25.01614101 -25.01614101 -25.01614101]
 [-24.92119495 -24.92119495 -24.92119495]
 [-24.46415925 -24.46415925 -24.46415925]
 [-24.18835058 -24.18835058 -24.18835058]]
[-3 -2 -1  0  1  2  3]


array([[-25.01614101, -24.92119495, -24.46415925],
       [-24.71923002, -25.01614101, -24.92119495],
       [-26.09829239, -24.71923002, -25.01614101],
       [-25.07107905, -26.09829239, -24.71923002],
       [  0.        , -25.07107905, -26.09829239]])

In [7]:
print(band_mx(10, 10, half_band_size=3, return_sparse=False))

[-24.20699376 -25.4440164  -25.54174161 -24.33191448 -25.11553705
 -26.07239115 -23.50164298]
[[-24.20699376 -24.20699376 -24.20699376 -24.20699376 -24.20699376
  -24.20699376 -24.20699376 -24.20699376 -24.20699376 -24.20699376]
 [-25.4440164  -25.4440164  -25.4440164  -25.4440164  -25.4440164
  -25.4440164  -25.4440164  -25.4440164  -25.4440164  -25.4440164 ]
 [-25.54174161 -25.54174161 -25.54174161 -25.54174161 -25.54174161
  -25.54174161 -25.54174161 -25.54174161 -25.54174161 -25.54174161]
 [-24.33191448 -24.33191448 -24.33191448 -24.33191448 -24.33191448
  -24.33191448 -24.33191448 -24.33191448 -24.33191448 -24.33191448]
 [-25.11553705 -25.11553705 -25.11553705 -25.11553705 -25.11553705
  -25.11553705 -25.11553705 -25.11553705 -25.11553705 -25.11553705]
 [-26.07239115 -26.07239115 -26.07239115 -26.07239115 -26.07239115
  -26.07239115 -26.07239115 -26.07239115 -26.07239115 -26.07239115]
 [-23.50164298 -23.50164298 -23.50164298 -23.50164298 -23.50164298
  -23.50164298 -23.50164298 -2

In [13]:
np.linalg.svd(band_mx(10, 10, half_band_size=1, return_sparse=False))

[-57.61569273  -5.6685512  -77.90357522]
[[-57.61569273 -57.61569273 -57.61569273 -57.61569273 -57.61569273
  -57.61569273 -57.61569273 -57.61569273 -57.61569273 -57.61569273]
 [ -5.6685512   -5.6685512   -5.6685512   -5.6685512   -5.6685512
   -5.6685512   -5.6685512   -5.6685512   -5.6685512   -5.6685512 ]
 [-77.90357522 -77.90357522 -77.90357522 -77.90357522 -77.90357522
  -77.90357522 -77.90357522 -77.90357522 -77.90357522 -77.90357522]]
[-1  0  1]


(array([[ 0.13528755,  0.1358756 , -0.26899614,  0.24749798, -0.3958635 ,
          0.31076809, -0.50089662,  0.28787983, -0.4844114 ,  0.08893584],
        [ 0.23268017, -0.23687214, -0.37288211, -0.41503163, -0.36675915,
         -0.479562  , -0.22123363, -0.39104027, -0.03703807, -0.10362714],
        [ 0.33226306,  0.32499963, -0.43623933,  0.38795677, -0.20828014,
          0.15103411,  0.24273285, -0.14580228,  0.53515296, -0.10199578],
        [ 0.38784261, -0.3995913 , -0.29670397, -0.3332632 ,  0.12352263,
          0.16922421,  0.29828934,  0.55384676,  0.05914121,  0.21838537],
        [ 0.42661111,  0.41308762, -0.1047313 ,  0.09043194,  0.44892149,
         -0.33584187,  0.20891017, -0.10017156, -0.49936497,  0.10417079],
        [ 0.41729679, -0.43047726,  0.13333821,  0.15288166,  0.31879593,
          0.42358714, -0.1986743 , -0.38573835, -0.07738876, -0.35226318],
        [ 0.38774971,  0.37636564,  0.34696297, -0.3081667 ,  0.10794553,
         -0.07863354, -0.4997322