In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
import scipy as sp
import scipy.sparse
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
from generate_matrices import band_mx

In [5]:
band_mx(5, 3, half_band_size=3)

[-24.98373105 -25.75552193 -22.96455279 -26.38817053 -24.62220085
 -26.37779635 -24.94882001]
[[-24.98373105 -24.98373105 -24.98373105]
 [-25.75552193 -25.75552193 -25.75552193]
 [-22.96455279 -22.96455279 -22.96455279]
 [-26.38817053 -26.38817053 -26.38817053]
 [-24.62220085 -24.62220085 -24.62220085]
 [-26.37779635 -26.37779635 -26.37779635]
 [-24.94882001 -24.94882001 -24.94882001]]
[-3 -2 -1  0  1  2  3]


<5x3 sparse matrix of type '<class 'numpy.float64'>'
	with 14 stored elements (7 diagonals) in DIAgonal format>

In [6]:
band_mx(5, 3, half_band_size=3, return_sparse=False)

[-25.07107905 -26.09829239 -24.71923002 -25.01614101 -24.92119495
 -24.46415925 -24.18835058]
[[-25.07107905 -25.07107905 -25.07107905]
 [-26.09829239 -26.09829239 -26.09829239]
 [-24.71923002 -24.71923002 -24.71923002]
 [-25.01614101 -25.01614101 -25.01614101]
 [-24.92119495 -24.92119495 -24.92119495]
 [-24.46415925 -24.46415925 -24.46415925]
 [-24.18835058 -24.18835058 -24.18835058]]
[-3 -2 -1  0  1  2  3]


array([[-25.01614101, -24.92119495, -24.46415925],
       [-24.71923002, -25.01614101, -24.92119495],
       [-26.09829239, -24.71923002, -25.01614101],
       [-25.07107905, -26.09829239, -24.71923002],
       [  0.        , -25.07107905, -26.09829239]])

In [7]:
print(band_mx(10, 10, half_band_size=3, return_sparse=False))

[-24.20699376 -25.4440164  -25.54174161 -24.33191448 -25.11553705
 -26.07239115 -23.50164298]
[[-24.20699376 -24.20699376 -24.20699376 -24.20699376 -24.20699376
  -24.20699376 -24.20699376 -24.20699376 -24.20699376 -24.20699376]
 [-25.4440164  -25.4440164  -25.4440164  -25.4440164  -25.4440164
  -25.4440164  -25.4440164  -25.4440164  -25.4440164  -25.4440164 ]
 [-25.54174161 -25.54174161 -25.54174161 -25.54174161 -25.54174161
  -25.54174161 -25.54174161 -25.54174161 -25.54174161 -25.54174161]
 [-24.33191448 -24.33191448 -24.33191448 -24.33191448 -24.33191448
  -24.33191448 -24.33191448 -24.33191448 -24.33191448 -24.33191448]
 [-25.11553705 -25.11553705 -25.11553705 -25.11553705 -25.11553705
  -25.11553705 -25.11553705 -25.11553705 -25.11553705 -25.11553705]
 [-26.07239115 -26.07239115 -26.07239115 -26.07239115 -26.07239115
  -26.07239115 -26.07239115 -26.07239115 -26.07239115 -26.07239115]
 [-23.50164298 -23.50164298 -23.50164298 -23.50164298 -23.50164298
  -23.50164298 -23.50164298 -2

In [14]:
np.random.seed(1)
mx = band_mx(10, 10, half_band_size=1, return_sparse=False)
print(mx)

[ 56.21726818 -55.58782068 -51.40858761]
[[ 56.21726818  56.21726818  56.21726818  56.21726818  56.21726818
   56.21726818  56.21726818  56.21726818  56.21726818  56.21726818]
 [-55.58782068 -55.58782068 -55.58782068 -55.58782068 -55.58782068
  -55.58782068 -55.58782068 -55.58782068 -55.58782068 -55.58782068]
 [-51.40858761 -51.40858761 -51.40858761 -51.40858761 -51.40858761
  -51.40858761 -51.40858761 -51.40858761 -51.40858761 -51.40858761]]
[-1  0  1]
[[-55.58782068 -51.40858761   0.           0.           0.           0.
    0.           0.           0.           0.        ]
 [ 56.21726818 -55.58782068 -51.40858761   0.           0.           0.
    0.           0.           0.           0.        ]
 [  0.          56.21726818 -55.58782068 -51.40858761   0.           0.
    0.           0.           0.           0.        ]
 [  0.           0.          56.21726818 -55.58782068 -51.40858761   0.
    0.           0.           0.           0.        ]
 [  0.           0.           0.  

In [21]:
u, singular_vals, v = np.linalg.svd(mx)
singular_vals

array([ 117.34813882,  117.27850889,  106.45931448,  106.17026295,
         90.26282249,   89.56135248,   72.39620924,   71.00508212,
         60.00185082,   54.28409154])

In [27]:
np.linalg.cond(mx)

2.1617408616990343

In [88]:
from generate_matrices import band_mx_with_given_cond

In [89]:
print(band_mx_with_given_cond(10, 10, 5, cond=3000))
print('cond:', np.linalg.cond(band_mx_with_given_cond(10, 10, 5, cond=3000)))

[[  73.35508746 -117.89909322   36.80820152   56.38253766   -8.09941517
   -84.96340162    0.            0.            0.            0.        ]
 [  38.68779651   73.35508746 -117.89909322   36.80820152   56.38253766
    -8.09941517  -84.96340162    0.            0.            0.        ]
 [ -63.75808096   38.68779651   73.35508746 -117.89909322   36.80820152
    56.38253766   -8.09941517  -84.96340162    0.            0.        ]
 [ -26.23084779  -63.75808096   38.68779651   73.35508746 -117.89909322
    36.80820152   56.38253766   -8.09941517  -84.96340162    0.        ]
 [  -4.5549731   -26.23084779  -63.75808096   38.68779651   73.35508746
  -117.89909322   36.80820152   56.38253766   -8.09941517  -84.96340162]
 [  31.07088541   -4.5549731   -26.23084779  -63.75808096   38.68779651
    73.35508746 -117.89909322   36.80820152   56.38253766   -8.09941517]
 [   0.           31.07088541   -4.5549731   -26.23084779  -63.75808096
    38.68779651   73.35508746 -117.89909322   36.80820152 